services:
  frontend:
    build: &default-build
      context: ../
      dockerfile: ./frontend/Dockerfile.dev
      args:
        - NODE_VERSION=${NODE_VERSION}      # Gives control and is expanded in the starter service
    init: true                              # Need to run as PID 1 to handle os signals like SIGTERM to use Watch correctly
    environment: &default-environment
      NODE_ENV: development
    ports: 
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes: # I dont need to share this if 'create-frontend' just generates package-lock.json
      - node_modules:/app/node_modules
    pull_policy: build
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "${FRONTEND_PORT}"]
    develop:
      watch:
        - action: sync
          path: ./${FRONTEND_APP_DIR}
          target: /app
          ignore:
            - node_modules/
            - Dockerfile*
            - compose*.yaml
            - .*ignore
            - .env*
        - action: rebuild
          path: ./${FRONTEND_APP_DIR}/package.json

  # Bundler/Starter
  create-frontend:
    build: 
      <<: *default-build
      target: base                        # Special Docker build stage
    environment: *default-environment
    volumes:                              # It needs access to the service root dir
      - ./:/app
    volumes_from: # Read volume explanation above
      - frontend
    command: ["sh", "-c", "npx create-vite ${FRONTEND_APP_DIR:-.} && npm install ${FRONTEND_APP_DIR:+--prefix $FRONTEND_APP_DIR}"]
    profiles:
      - starter

volumes:
  node_modules: