include:
  - path:
    - ../commons/compose.tooling.yaml


services:
  frontend:
    init: true
    build: 
      context: ../
      dockerfile: ./frontend/Dockerfile.dev
      args: !override
        - NODE_VERSION=${NODE_VERSION}
    environment: 
      - PORT=${FRONTEND_PORT}
      - NODE_ENV=development
    ports: !override
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - node_modules:/app/node_modules:rw
    # profiles:
    #   - dev
    pull_policy: build
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "${FRONTEND_PORT}"]
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
            - Dockerfile*
            - compose*.yaml
            - .*ignore
            - .env*
        - action: rebuild
          path: ./package.json


########################
# Tools
########################
  npm:
    extends: 
      file: ../commons/compose.tooling.yaml
      service: node
    volumes:
      - node_modules:/app/node_modules:rw
    entrypoint: ["/usr/local/bin/npm"]

  create-frontend:
    extends: 
      file: ../commons/compose.tooling.yaml
      service: node
    command: ["sh", "-c", "npx create-vite . && npm install --include dev --verbose"]


volumes:
  node_modules: